# Generated by Django 3.1 on 2020-09-25 21:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_escuela', models.CharField(default='', max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Error en la longitud'), django.core.validators.MinLengthValidator(10, 'Error en la longitud')])),
                ('turno_escuela', models.CharField(default='', max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Error en la longitud'), django.core.validators.MinLengthValidator(6, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[0-9]*$', 'No se permiten letras')])),
                ('ambito_escuela', models.CharField(default='', max_length=6, validators=[django.core.validators.MaxLengthValidator(6, 'Error en la longitud'), django.core.validators.MinLengthValidator(5, 'Error de longitud mínima')])),
                ('centro_educativo', models.CharField(default='', max_length=80, validators=[django.core.validators.MaxLengthValidator(80, 'Error en la longitud'), django.core.validators.MinLengthValidator(5, 'Error de longitud mínima')])),
                ('control_escuela', models.CharField(default='', max_length=8, validators=[django.core.validators.MaxLengthValidator(8, 'Error en la longitud'), django.core.validators.MinLengthValidator(6, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[0-9]*$', 'No se permiten letras')])),
                ('domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad.domicilio', verbose_name='Domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lada', models.IntegerField(default=0, max_length=4, null=True, validators=[django.core.validators.MaxLengthValidator(4, 'Error en la longitud'), django.core.validators.MinLengthValidator(0, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ\\u00E0-\\u00FC ]+$', 'No se permiten caracteres especiales')])),
                ('telefono', models.IntegerField(default=0, max_length=5, null=True, validators=[django.core.validators.MaxLengthValidator(5, 'Error en la longitud'), django.core.validators.MinLengthValidator(0, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ\\u00E0-\\u00FC ]+$', 'No se permiten caracteres especiales')])),
                ('correo_electronico', models.CharField(default=0, max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50, 'Error en la longitud'), django.core.validators.MinLengthValidator(15, 'Error de longitud mínima')])),
                ('escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escuela.escuela', verbose_name='Escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_alumnos', models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(9999, 'Error en la longitud'), django.core.validators.MinLengthValidator(1, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ\\u00E0-\\u00FC ]+$', 'No se permiten caracteres especiales')], verbose_name='Total Alumnos:')),
                ('mujeres_alumnas', models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(999, 'Error en la longitud'), django.core.validators.MinLengthValidator(0, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ\\u00E0-\\u00FC ]+$', 'No se permiten caracteres especiales')], verbose_name='Mujeres:')),
                ('hombres_alumnos', models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(999, 'Error en la longitud'), django.core.validators.MinLengthValidator(0, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ\\u00E0-\\u00FC ]+$', 'No se permiten caracteres especiales')], verbose_name='Hombres:')),
                ('escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escuela.escuela', verbose_name='Escuela')),
            ],
        ),
    ]
