# Generated by Django 3.1 on 2020-09-25 21:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_domicilio', models.CharField(default='', max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'Error en la longitud'), django.core.validators.MinLengthValidator(5, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ\\u00E0-\\u00FC ]+$', 'No se permiten caracteres especiales')])),
                ('numero_externo', models.CharField(default='', max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Error en la longitud'), django.core.validators.MinLengthValidator(1, 'Error de longitud mínima')])),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_entidad', models.IntegerField(default=32, validators=[django.core.validators.MinLengthValidator(32, 'El valor mínimo permitido es 32'), django.core.validators.MaxLengthValidator(32)], verbose_name='Clave Entidad:')),
                ('nombre_entidad', models.CharField(default='', max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Error en la longitud'), django.core.validators.MinLengthValidator(5, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ\\u00E0-\\u00FC ]+$', 'No se permiten caracteres especiales')])),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitud_msnm', models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0, 'El valor mínimo permitido es 32'), django.core.validators.MaxLengthValidator(9999, 'El valor máximo permitido son 9999')])),
                ('longitud', models.DecimalField(decimal_places=10, default=0, max_digits=14, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(999000000, 'El valor máximo permitido son 999000000')])),
                ('latitud', models.DecimalField(decimal_places=8, default=0, max_digits=12, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(999000000, 'El valor máximo permitido son 999000000')])),
                ('longitud_gms', models.CharField(default='', max_length=20, validators=[django.core.validators.MaxLengthValidator(20, 'Error en la longitud'), django.core.validators.MinLengthValidator(16, 'Error de longitud mínima')])),
                ('latitud_gms', models.CharField(default='', max_length=8, validators=[django.core.validators.MaxLengthValidator(8), django.core.validators.MinLengthValidator(7)])),
                ('domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad.domicilio', verbose_name='Docimiclio')),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad.entidad', verbose_name='Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_municipio', models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0, 'El valor mínimo permitido es 32'), django.core.validators.MaxLengthValidator(100, 'El valor máximo permitido son 100')], verbose_name='Clave Municipio:')),
                ('nombre_municipio', models.CharField(default='', max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Error en la longitud'), django.core.validators.MinLengthValidator(5, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ\\u00E0-\\u00FC ]+$', 'No se permiten caracteres especiales')])),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad.entidad', verbose_name='Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_localidad', models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0, 'El valor mínimo permitido es 32'), django.core.validators.MaxLengthValidator(1000, 'El valor máximo permitido son 1000')], verbose_name='Clave Localidad:')),
                ('nombre_localidad', models.CharField(default='', max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'Error en la longitud'), django.core.validators.MinLengthValidator(5, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ\\u00E0-\\u00FC ]+$', 'No se permiten caracteres especiales')])),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad.entidad', verbose_name='Entidad')),
            ],
        ),
        migrations.AddField(
            model_name='domicilio',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad.entidad', verbose_name='Entidad'),
        ),
    ]
