CREATE TABLE IF NOT EXISTS `ENTIDAD` (
  `ID_ENTIDAD` int  PRIMARY KEY,
  `ENTIDAD` char(9) NOT NULL default 'ZACATECAS',
  `ID_DOMICILIO` int,
  `ID_LOCALIDAD` int,
  `ID_MUNICIPIO` int,
	FOREIGN KEY (`ID_DOMICILIO`) REFERENCES DOMICILIO( `ID_DOMICILIO`),
    FOREIGN KEY (`ID_LOCALIDAD`) REFERENCES LOCALIDAD( `ID_LOCALIDAD`),
    FOREIGN KEY (`ID_MUNICIPIO`) REFERENCES MUNICIPIO( `ID_MUNICIPIO`)
);

CREATE TABLE IF NOT EXISTS `MUNICIPIO` (
  `ID_MUNICIPIO` int  PRIMARY KEY,
  `MUNICIPIO` varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS `LOCALIDAD` (
  `ID_LOCALIDAD` int  PRIMARY KEY,
  `LOCALIDAD` varchar(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS `DOMICILIO` (
  `ID_DOMICILIO` char(10)  PRIMARY KEY,
  `DOMICILIO` varchar(50) NOT NULL,
  `NUMERO_EXTERIOR` char(5) DEFAULT NULL,
  `CODIGO_POSTAL` char(5),
  `ENTRE_CALLE` varchar(50) DEFAULT 'NINGUNO',
  `Y_CALLE` varchar(50) DEFAULT 'NINGUNO',
  `CALLE_POSTERIOR` varchar(50) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `UBICACION` (
  `ID_UBICACION` int AUTO_INCREMENT  PRIMARY KEY,
  `ID_ALTITUD` int,
  `LONGITUD` char(15) NOT NULL,
  `LATITUD` char(15) NOT NULL,
  `LONGITUD_GMS` char(15) NOT NULL,
  `LATITUD_GMS` char(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS `SALONES` (
  `ID_SALONES` int AUTO_INCREMENT  PRIMARY KEY,
  `SALONES_EXISTENTES` int DEFAULT 0,
  `SALONES_EN_USO` int DEFAULT 0,
  `TOTAL` int DEFAULT 0,
  `LABORATORIOS` int DEFAULT 0,
  `TALLERES` int DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `LIMPEZA` (
  `ID_LIMPEZA` int AUTO_INCREMENT  PRIMARY KEY,
  `FECHA_LIMPEZA` date,
  `ID_PERSONAL` int,
  `ID_SALONES` int,
	FOREIGN KEY (`ID_PERSONAL`) REFERENCES PERSONAL( `ID_PERSONAL`),
    FOREIGN KEY (`ID_SALONES`) REFERENCES SALONES( `ID_SALONES`)
);

CREATE TABLE IF NOT EXISTS `PERSONAL` (
  `ID_PERSONAL` int AUTO_INCREMENT  PRIMARY KEY,
  `PERSONAL_MUJERES` int DEFAULT 0,
  `PERSONAL_HOMBRE` int DEFAULT 0,
  `TOTAL_PERSONAL` int DEFAULT 0
  
);

CREATE TABLE IF NOT EXISTS `COMPUTADORAS` (
  `ID_COMPUTADORAS` int AUTO_INCREMENT  PRIMARY KEY,
  `COMPUTADORAS_EN_OPERACION_MAS_INTERNET` int DEFAULT 0,
  `COMPUTADORAS_EN_OPERACION_USO_EDUCATIVO` int DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `EQUIPO` (
  `ID_EQUIPO` int AUTO_INCREMENT  PRIMARY KEY,
  `ID_COMPUTADORAS` int,
	FOREIGN KEY (`ID_COMPUTADORAS`) REFERENCES COMPUTO( `ID_COMPUTADORAS`)
);



CREATE TABLE IF NOT EXISTS `PERIODO`(
  `ID_PERIODO` int AUTO_INCREMENT PRIMARY KEY,
  `PERIODO` char(9) NOT NULL,
  `NIVEL EDUCATIVO` char(60),
  `TIPO_PERIODO` varchar(60) NOT NULL,
  `SERVICIO EDUCATIVO` varchar(60)NOT NULL
  
);

CREATE TABLE IF NOT EXISTS `DOCENTES` (
  `ID_DOCENTE` int AUTO_INCREMENT  PRIMARY KEY,
  `DOCENTES_MUJERES` int DEFAULT 0,
  `DOCENTES_HOMBRE` int DEFAULT 0,
  `TOTAL_DOCENTES` int DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `ALUMNOS` (
  `ID_ALUMNOS` int AUTO_INCREMENT  PRIMARY KEY,
  `ALUMNOS_MUJERES` int DEFAULT 0,
  `ALUMNOS_HOMBRE` int DEFAULT 0,
  `TOTAL_ALUMNOS` int DEFAULT 0
);

CREATE TABLE IF NOT EXISTS`GRUPO` (
  `ID_GRUPO` int AUTO_INCREMENT  PRIMARY KEY,
  `ID_PERIODO` int,
  `TOTAL` int DEFAULT 0,
  `ID_ALUMNO` int,
  `ID_SALONES` int,
    FOREIGN KEY (`ID_PERIODO`) REFERENCES PERIODO( `ID_PERIODO`),
	FOREIGN KEY (`ID_ALUMNO`) REFERENCES ALUMNOS( `ID_ALUMNO`),
	FOREIGN KEY (`ID_SALONES`) REFERENCES SALONES( `ID_SALONES`)
);

CREATE TABLE IF NOT EXISTS `CONTACTO` (
  `ID_TELEFONO` int AUTO_INCREMENT  PRIMARY KEY,
  `LADA` char(4) DEFAULT NULL,
  `TELEFONO` char(10),
  `CORREO_ELECTRONICO` varchar(100) DEFAULT NULL unique
  
);
 

CREATE TABLE IF NOT EXISTS `ESCUELA` (
  `ID_DOMICILIO` int,
  `ID_TELEFONO` int,
  `ID_ALUMNO` int,
  `TURNO` varchar(15)  NOT NULL,
  `AMBITO` varchar(50)  NOT NULL,
    FOREIGN KEY (`ID_TELEFONO`) REFERENCES CONTACTO( `ID_TELEFONO`),
    FOREIGN KEY (`ID_ALUMNO`) REFERENCES ALUMNOS( `ID_ALUMNO`),
	FOREIGN KEY (`ID_DOMICILIO`) REFERENCES DOMICILIO( `DOMICILIO`),
);