# Generated by Django 3.1 on 2020-09-25 21:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo.salones', verbose_name='Salones')),
            ],
        ),
        migrations.CreateModel(
            name='Computadoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computadoras_operacion', models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(999, 'Error en la longitud'), django.core.validators.MinLengthValidator(1, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ\\u00E0-\\u00FC ]+$', 'No se permiten caracteres especiales')], verbose_name='Computadoras en operacion')),
                ('computadoras_operacion_internet', models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(999, 'Error en la longitud'), django.core.validators.MinLengthValidator(1, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ\\u00E0-\\u00FC ]+$', 'No se permiten caracteres especiales')], verbose_name='Computadoras en operacion con internet')),
                ('computadoras_operacion_uso_educativo', models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(999, 'Error en la longitud'), django.core.validators.MinLengthValidator(1, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ\\u00E0-\\u00FC ]+$', 'No se permiten caracteres especiales')], verbose_name='Computadoras en operacion con internet')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo', verbose_name='Equipo')),
            ],
        ),
    ]
